
services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=hadoop_cluster
    env_file:
      - ./hadoop.env
    networks:
      - hadoop_network

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    ports:
      - 9864:9864
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      - SERVICE_PRECONDITION=namenode:9870
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode
    networks:
      - hadoop_network

  nifi:
    image: apache/nifi:latest
    container_name: nifi
    restart: always
    ports:
      - 8080:8080
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=false
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
    volumes:
      - /Users/macbookpro/Documents/Matkul_S2/DWDIB/MDW/nifi-flows:/nifi_data
      - /Users/macbookpro/Documents/Matkul_S2/DWDIB/MDW/HDFS_Data/nifi_hadoop:/nifi_hadoop_data
      - ./nifi-flows/core-site.xml:/opt/nifi/nifi-current/conf/core-site.xml
      - ./nifi-flows/hdfs-site.xml:/opt/nifi/nifi-current/conf/hdfs-site.xml
    
    # volumes:
    #   - nifi_conf:/opt/nifi/nifi-current/conf
    #   - nifi_state:/opt/nifi/nifi-current/state
    #   - nifi_content:/opt/nifi/nifi-current/content_repository
    #   - nifi_database:/opt/nifi/nifi-current/database_repository
    #   - nifi_flowfile:/opt/nifi/nifi-current/flowfile_repository
    #   - nifi_provenance:/opt/nifi/nifi-current/provenance_repository
    #   - ./nifi-flows:/opt/nifi/nifi-current/flows
    depends_on:
      - zookeeper
    networks:
      - hadoop_network

  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    restart: always
    ports:
      - 8090:8080
      - 7077:7077
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./spark-apps:/opt/spark-apps
      - ./spark-data:/opt/spark-data
    networks:
      - hadoop_network

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    restart: always
    ports:
      - 8091:8081
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./spark-apps:/opt/spark-apps
      - ./spark-data:/opt/spark-data
    depends_on:
      - spark-master
    networks:
      - hadoop_network

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    restart: always
    ports:
      - 10000:10000
    environment:
      - HIVE_CORE_CONF_javax_jdo_option_ConnectionURL=jdbc:postgresql://hive-metastore/metastore
      - SERVICE_PRECONDITION=hive-metastore:9083
    volumes:
      - ./hive-scripts:/opt/hive-scripts
    depends_on:
      - hive-metastore
    networks:
      - hadoop_network

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    restart: always
    ports:
      - 9083:9083
    environment:
      - SERVICE_PRECONDITION=namenode:9870 datanode:9864 postgres-metastore:5432
    volumes:
      - ./hive-scripts:/opt/hive-scripts
    depends_on:
      - postgres-metastore
    networks:
      - hadoop_network

  postgres-metastore:
    image: postgres:12
    container_name: postgres-metastore
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=metastore
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hadoop_network

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    restart: always
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - hadoop_network

networks:
  hadoop_network:
    driver: bridge

volumes:
  hadoop_namenode:
  hadoop_datanode:
  nifi_conf:
  nifi_state:
  nifi_content:
  nifi_database:
  nifi_flowfile:
  nifi_provenance:
  postgres_data: